version: '1.0'
motor: DisateQ CPE v4.0
fuente:
  tipo: dbf
  ruta: D:/FFEESUNAT/test
comprobantes:
  tabla: enviosffee
  filtro: FLAG_ENVIO = '2'
  campos:
    tipo_doc: TIPO_FACTU
    serie: SERIE_FACT
    numero: NUMERO_FAC
    fecha: FECHA_DOCU
items:
  tabla: detalleventa
  join_campo_comprobante: NUMERO_FAC
  filtro: ''
  campos:
    codigo: CODIGO_PRO
    descripcion: ''
    cantidad: CANTIDAD_P
    precio: PRECIO_UNI
    subtotal: MONTO_PEDI
    igv: IGV_PEDIDO
    total: REAL_PEDID
    cantidad_fraccion: FRACCION_P
lookups:
  lookup_descripcion:
    tabla: productox
    campo_clave: CODIGO_PRO
    campo_valor: DESCRIPCIO
transformaciones:
  tipo_doc:
    B: '03'
    F: '01'
    T: '03'
  fecha:
    formato_origen: YYYYMMDD
