cliente_id: farmacia_central

source:
  type: dbf
  path: D:\FFEESUNAT\Test
  encoding: latin-1

comprobantes:
  tabla: enviosffee
  flag_lectura:
    campo: FLAG_ENVIO
    valor: 2
  flag_escritura:
    campo: FLAG_ENVIO
    enviado: 3
    error: 4

notas:
  tabla: notacredito
  tipo_registro: anulacion
  flag_lectura:
    campo_pendiente:  PENDIENTE_
    valor_pendiente:  '2'
    campo_tipo_movim: TIPO_MOVIM
    valor_tipo_movim: 2
  serie_prefijos:
    F: FC
    B: BC
  tipo_comprobante_map:
    F: '1'
    B: '2'

items:
  tabla: detalleventa

totales:
  tabla: factura

productos:
  tabla: productox
  join_campo: CODIGO_PRO

motivos:
  tabla: motivonota

cliente_varios:
  tipo_doc: '-'
  num_doc:  '00000000'
  nombre:   CLIENTE VARIOS
