empresa:
  alias: LOCAL PRINCIPAL
  nombre_comercial: Farmacia Central
  razon_social: FARMACIA CENTRAL S.A.C.
  ruc: '10715460632'
envio:
  endpoints: []
fuente:
  rutas:
  - D:/FFEESUNAT/test
  tipo: dbf
instalador:
  clave: '1234'
licencia:
  clave: ''
  endpoint_validacion: https://licenses.disateq.com/v1/validate
observaciones: 'Cliente migrado desde sistema legacy FoxPro.

  Serie B001 activa desde correlativo 16377.

  Validar series con SUNAT antes de activar F001.

  '
series:
  boleta:
  - activa: true
    correlativo_inicio: 16377
    serie: B001
  factura:
  - activa: true
    correlativo_inicio: 0
    serie: F001
  nota_credito: []
  nota_debito: []
